/// Flutter icons MilitaryFonts
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MilitaryFonts
///      fonts:
///       - asset: fonts/MilitaryFonts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MilitaryFonts {
  MilitaryFonts._();

  static const _kFontFam = 'MilitaryFonts';
  static const _kFontPkg = null;

  static const IconData tank = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData missile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData missile2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warship = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tank2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
